export const LINE_TYPE_CHIPHI = {
  QUANG: 'QUANG',
  CHI_PHI_KHAC: 'CHI_PHI_KHAC',
  QUANG_HOI: 'QUANG_HOI',
  CHI_PHI_SX_GANG_LONG: 'CHI_PHI_SX_GANG_LONG',
  DON_GIA_NGHIEN: 'DON_GIA_NGHIEN',
  CHI_PHI_NGHIEN: 'CHI_PHI_NGHIEN',
};